[package]
name = "ellie_engine"
version = "2.7.0"
authors = ["Ahmetcan Aksu <ahmetcanaksu@behemehal.net>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

ellie_core = {path = "core", version = "1.0.0"}
ellie_parser = {path = "parser", version = "1.0.0"}
ellie_runtime = {path = "runtime", version = "0.1.0"}

[lib]
name = "ellie_lang"
path = "src/lib.rs"

[[bin]]
name = "ellie"
test = false
bench = false

[[bin]]
name = "value_test"
test = false
bench = false

[[bin]]
name = "type_test"
test = false
bench = false

[[bench]]
name = "benches"
harness = false

[build-dependencies]
ellie_core = {path = "core", version = "1.0.0"}
cbindgen = "*"

[dev-dependencies]
criterion = { version = "0.3", features= ["html_reports"]}
